/*
AL CLICK GENERO NUMERI RANDOM DA 1 A 9 E SE IL NUMERO E' MAGGIORE O UGUALE A 5 IL QUADRATO DIVENTA GIALLO
ALTRIMENTI IL QUADRATO DIVENTA VERDE.
IL NUMERO OTTENUTO APPARE AL CENTRO DEL QUADRATO
BONUS: OTTIMIZZARE CON HANDLEBARS
*/

$(document).ready(function() {

});
